import Head from 'next/head'
import Image from 'next/image'
import { Fragment } from 'react'
import Features from '../components/home/Features/Features'
import Hero from '../components/home/Hero/Hero'
import Procedure from '../components/home/Procedure/Procedure'
import Testimonial from '../components/home/Testimonial/Testimonial'
import styles from '../styles/Home.module.css'
import Layout from '../UI/Layout'

export default function Home() {
  return (
  <Fragment>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Layout>
      <main className={styles.home_main}>
        <Hero/>
        <Features/>
        <Procedure/>
        {/* <Testimonial/> */}
      </main>
    </Layout>
  </Fragment>
  )
}
